/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.InternalCadastroProdutoController;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/**
 *
 * @author kaliez
 */
public class InternalCadastroProduto extends javax.swing.JInternalFrame {

    
     private final InternalCadastroProdutoController controller;
    
    
    public InternalCadastroProduto() {
        initComponents();
        this.controller = new InternalCadastroProdutoController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadastroUsuario3 = new javax.swing.JPanel();
        jSpinnerQuantidade = new javax.swing.JSpinner();
        jTextNomeProd = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jTextPrecoCusto = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel49 = new javax.swing.JLabel();
        jButtonCadastrar3 = new javax.swing.JButton();
        jButtonSair1 = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();
        jTextPrecoVenda = new javax.swing.JTextField();
        jButtonLimpar3 = new javax.swing.JButton();
        jLabel56 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jTextFabricanteCnpj = new javax.swing.JTextField();
        jComboBoxNomeFab = new javax.swing.JComboBox<>();

        jLabel43.setText("Nome Fabricante:");

        jLabel44.setText("Preço de Custo(R$):");

        jLabel45.setText("Preco de Venda(R$):");

        jLabel49.setText("Cadastro de Produto");

        jButtonCadastrar3.setText("Cadastrar");
        jButtonCadastrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrar3ActionPerformed(evt);
            }
        });

        jButtonSair1.setText("Sair");
        jButtonSair1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonSair1MousePressed(evt);
            }
        });
        jButtonSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSair1ActionPerformed(evt);
            }
        });

        jLabel54.setText("Nome Produto:");

        jButtonLimpar3.setText("Limpar");
        jButtonLimpar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpar3ActionPerformed(evt);
            }
        });

        jLabel56.setText("Quantidade:");

        jLabel46.setText("Cnpj Fabricante:");

        jTextFabricanteCnpj.setEnabled(false);
        jTextFabricanteCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFabricanteCnpjActionPerformed(evt);
            }
        });

        jComboBoxNomeFab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxNomeFab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNomeFabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroUsuario3Layout = new javax.swing.GroupLayout(jPanelCadastroUsuario3);
        jPanelCadastroUsuario3.setLayout(jPanelCadastroUsuario3Layout);
        jPanelCadastroUsuario3Layout.setHorizontalGroup(
            jPanelCadastroUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroUsuario3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelCadastroUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroUsuario3Layout.createSequentialGroup()
                        .addComponent(jLabel54)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelCadastroUsuario3Layout.createSequentialGroup()
                        .addComponent(jButtonSair1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLimpar3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 398, Short.MAX_VALUE)
                        .addComponent(jButtonCadastrar3)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroUsuario3Layout.createSequentialGroup()
                        .addComponent(jSeparator4)
                        .addContainerGap())
                    .addGroup(jPanelCadastroUsuario3Layout.createSequentialGroup()
                        .addGroup(jPanelCadastroUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel49)
                            .addGroup(jPanelCadastroUsuario3Layout.createSequentialGroup()
                                .addGroup(jPanelCadastroUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextPrecoCusto)
                                    .addComponent(jTextPrecoVenda)
                                    .addComponent(jLabel43))
                                .addGap(39, 39, 39)
                                .addGroup(jPanelCadastroUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel46)
                                    .addGroup(jPanelCadastroUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSpinnerQuantidade)
                                        .addComponent(jTextFabricanteCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanelCadastroUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBoxNomeFab, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextNomeProd, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)))
                        .addContainerGap(381, Short.MAX_VALUE))))
        );
        jPanelCadastroUsuario3Layout.setVerticalGroup(
            jPanelCadastroUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroUsuario3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabel54)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxNomeFab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCadastroUsuario3Layout.createSequentialGroup()
                        .addComponent(jLabel44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCadastroUsuario3Layout.createSequentialGroup()
                        .addGroup(jPanelCadastroUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelCadastroUsuario3Layout.createSequentialGroup()
                                .addComponent(jLabel46)
                                .addGap(30, 30, 30))
                            .addComponent(jTextFabricanteCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCadastroUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroUsuario3Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jSpinnerQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel56))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addGroup(jPanelCadastroUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCadastrar3)
                    .addGroup(jPanelCadastroUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSair1)
                        .addComponent(jButtonLimpar3)))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCadastroUsuario3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCadastroUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void exibeMsg(String msg) {
        JOptionPane.showMessageDialog(null, msg);
    }
    
    private void jButtonCadastrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrar3ActionPerformed

        this.controller.cadastrarNoSistema();
    }//GEN-LAST:event_jButtonCadastrar3ActionPerformed

    private void jButtonSair1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSair1MousePressed

    }//GEN-LAST:event_jButtonSair1MousePressed

    private void jButtonSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSair1ActionPerformed

        this.controller.sair();
    }//GEN-LAST:event_jButtonSair1ActionPerformed

    private void jButtonLimpar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpar3ActionPerformed

        this.controller.limpar();
    }//GEN-LAST:event_jButtonLimpar3ActionPerformed

    private void jTextFabricanteCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFabricanteCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFabricanteCnpjActionPerformed

    private void jComboBoxNomeFabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNomeFabActionPerformed
        // TODO add your handling code here:
        if(evt.getActionCommand().equals("comboBoxChanged") && this.controller != null){
            this.controller.preencheCnpjWithFabricante();
        }
    }//GEN-LAST:event_jComboBoxNomeFabActionPerformed

    public JSpinner getjSpinnerQuantidade() {
        return jSpinnerQuantidade;
    }

    public void setjSpinnerQuantidade(JSpinner jSpinnerQuantidade) {
        this.jSpinnerQuantidade = jSpinnerQuantidade;
    }


    public JTextField getjTextNomeProd() {
        return jTextNomeProd;
    }

    public void setjTextNomeProd(JTextField jTextNomeProd) {
        this.jTextNomeProd = jTextNomeProd;
    }

    public JTextField getjTextPrecoCusto() {
        return jTextPrecoCusto;
    }

    public void setjTextPrecoCusto(JTextField jTextPrecoCusto) {
        this.jTextPrecoCusto = jTextPrecoCusto;
    }

    public JTextField getjTextFabricanteCnpj() {
        return jTextFabricanteCnpj;
    }

    public void setjTextFabricanteCnpj(JTextField jTextFabricanteCnpj) {
        this.jTextFabricanteCnpj = jTextFabricanteCnpj;
    }


    public JTextField getjTextPrecoVenda() {
        return jTextPrecoVenda;
    }

    public void setjTextPrecoVenda(JTextField jTextPrecoVenda) {
        this.jTextPrecoVenda = jTextPrecoVenda;
    }

    public JComboBox<String> getjComboBoxNomeFab() {
        return jComboBoxNomeFab;
    }

    public void setjComboBoxNomeFab(JComboBox<String> jComboBoxNomeFab) {
        this.jComboBoxNomeFab = jComboBoxNomeFab;
    }


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar3;
    private javax.swing.JButton jButtonLimpar3;
    private javax.swing.JButton jButtonSair1;
    private javax.swing.JComboBox<String> jComboBoxNomeFab;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JPanel jPanelCadastroUsuario3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSpinner jSpinnerQuantidade;
    private javax.swing.JTextField jTextFabricanteCnpj;
    private javax.swing.JTextField jTextNomeProd;
    private javax.swing.JTextField jTextPrecoCusto;
    private javax.swing.JTextField jTextPrecoVenda;
    // End of variables declaration//GEN-END:variables
}
